#model_name_or_path: LLMs/Models/Qwen25-7b-hf
model_name_or_path: LLMs/Models/llama-2-13b

#adapter_name_or_path: LLMs/MyModels/Qwen25-7b_WebQSP-sparql
adapter_name_or_path: LLMs/MyModels/Llama-2-13b_CWQ-sparql

finetuning_type: lora

#template: qwen #llama2
template: default

infer_dtype: bfloat16
trust_remote_code: true
