"""
IRI normalisation, term stringification, and property-path serialisation.

All functions accept a prefix_map so callers never have to import COMMON_PREFIXES
directly; the map is built once in algebra_transform.extract_prefix_map and
threaded through the call stack.
"""

from __future__ import annotations
from typing import Union

SExp = Union[str, list]
PrefixMap = dict[str, str]


# ---------------------------------------------------------------------------
# Core IRI normalisation
# ---------------------------------------------------------------------------

def normalize_iri(token: str, prefix_map: PrefixMap) -> str:
    """
    Resolve a single token to its canonical display form:
      - Blank nodes generated by Jena (??x) -> []
      - Already-full IRIs (<...>) -> unchanged
      - Variables (?x) -> unchanged
      - Typed literals ("val"^^prefix:local) -> "val"^^<full-uri>
      - Plain literals ("...") -> unchanged
      - Prefixed names (prefix:local) -> <full-uri>
      - Anything unrecognised -> unchanged
    """
    if token.startswith("??"):
        return "[]"

    if token.startswith("<") and token.endswith(">"):
        return token

    if token.startswith("?"):
        return token

    if token.startswith('"'):
        if "^^" in token:
            val, typ = token.split("^^", 1)
            if typ.startswith("<"):
                return f"{val}^^{typ}"
            if ":" in typ:
                prefix, local = typ.split(":", 1)
                if prefix in prefix_map:
                    return f'{val}^^<{prefix_map[prefix]}{local}>'
        return token

    if ":" in token:
        prefix, local = token.split(":", 1)
        if prefix in prefix_map:
            return f"<{prefix_map[prefix]}{local}>"

    return token


# ---------------------------------------------------------------------------
# Convenience wrappers
# ---------------------------------------------------------------------------

def term_to_str(term: str, prefix_map: PrefixMap) -> str:
    """Normalise a triple subject / predicate / object term."""
    return normalize_iri(term, prefix_map)


def sexp_to_str(node: SExp, prefix_map: PrefixMap) -> str:
    """
    Generic s-expression to string, used only as a last-resort fallback
    for nodes that no other handler recognises.
    """
    if isinstance(node, str):
        return normalize_iri(node, prefix_map)
    return "(" + " ".join(sexp_to_str(child, prefix_map) for child in node) + ")"


# ---------------------------------------------------------------------------
# Property-path serialisation
# ---------------------------------------------------------------------------

def path_to_str(node: SExp, prefix_map: PrefixMap) -> str:
    """Render a Jena property-path node as a SPARQL path expression."""
    if isinstance(node, str):
        return normalize_iri(node, prefix_map)

    op = node[0]
    child_str = lambda n: path_to_str(n, prefix_map)  # noqa: E731

    _UNARY = {
        "path*":   lambda: child_str(node[1]) + "*",
        "path+":   lambda: child_str(node[1]) + "+",
        "path?":   lambda: child_str(node[1]) + "?",
        "pathinv": lambda: "^" + child_str(node[1]),
        "pathnot": lambda: "!" + child_str(node[1]),
    }
    if op in _UNARY:
        return _UNARY[op]()

    if op in ("seq", "pathseq"):
        return "/".join(child_str(c) for c in node[1:])
    if op in ("alt", "pathalt"):
        return "|".join(child_str(c) for c in node[1:])

    # Fallback to generic s-expression form.
    return sexp_to_str(node, prefix_map)