import re
import json
import subprocess
import os

JAVA = os.path.join(os.environ.get("JAVA_HOME"), "bin", "java")
JENA_HOME = os.environ.get("JENA_HOME")

classpath = os.path.join(JENA_HOME, "lib", "*") + ":" + os.path.join(os.getcwd(), "ApacheJena")

COMMON_PREFIXES = {
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "wd": "http://www.wikidata.org/entity/",
    "wdt": "http://www.wikidata.org/prop/direct/",
    "p": "http://www.wikidata.org/prop/",
    "ps": "http://www.wikidata.org/prop/statement/",
    "pq": "http://www.wikidata.org/prop/qualifier/",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "wikibase": "http://wikiba.se/ontology#",
    "schema": "https://schema.org/",
}

def fix_sparql_for_jena(sparql: str) -> str:
    sparql_fixed = ' '.join(sparql.split())
    sparql_fixed = re.sub(r'\s+OR\s+', ' || ', sparql_fixed, flags=re.IGNORECASE)

    def filter_or_replacer(match):
        inner = match.group(1).strip()
        parts = [p.strip() for p in inner.split('||')]
        wrapped = ' || '.join(f'({p})' for p in parts)
        return f'FILTER ({wrapped})'
    sparql_fixed = re.sub(r'FILTER\s*\((.*?)\)', filter_or_replacer, sparql_fixed)
    sparql_fixed = re.sub(r'\bxsd:datetime\s*\(', 'xsd:dateTime(', sparql_fixed, flags=re.IGNORECASE)


    for prefix, uri in COMMON_PREFIXES.items():
        if f"PREFIX {prefix}:" not in sparql_fixed:
            sparql_fixed = f"PREFIX {prefix}: <{uri}>\n" + sparql_fixed
    return sparql_fixed


def sparql_to_algebra(sparql: str) -> str:
    try:
        result = subprocess.run(
            [
                JAVA,
                "-cp",
                classpath,
                "SparqlToSExpr",
                sparql
            ],
            capture_output=True, text=True, timeout=30
        )
        if result.returncode != 0:
            raise RuntimeError(
                f"Jena execution failed (exit {result.returncode}):\n"
                f"STDERR: {result.stderr}"
            )
        res = result.stdout
        print("=== Algebra ===")
        print(res)
        return res
    except Exception as e:
        print(f"Jena execution failed: {e}.\n")
        return None


def algebra_to_sparql(algebra: str) -> str:
    try:
        result = subprocess.run(
            [
                JAVA_HOME,
                "-cp",
                f"{JENA_HOME}:{JENA_HOME}/lib/*",
                "SExprToSparql",
                algebra
            ],
            capture_output=True, text=True, timeout=30
        )
        if result.returncode != 0:
            raise RuntimeError(
                f"Jena execution failed (exit {result.returncode}):\n"
                f"STDERR: {result.stderr}"
            )
        res = result.stdout
        print("=== SPARQL ===")
        print(res)
        return res
    except Exception as e:
        print(f"Jena execution failed: {e}.\n")
        return None


# Algebra to AST ---------------------------------------------

def tokenize_sexp(s: str) -> list[str]:
    return re.findall(
        r'\(|\)|\[|\]'           # parens and brackets
        r'|"[^"]*"\^\^[^\s()\[\]]+'  # typed literals: "val"^^type
        r'|"[^"]*"'              # plain strings
        r'|[^\s()\[\]]+',        # everything else
        s
    )

def parse_tokens(tokens: list[str], i: int) -> tuple:
    if tokens[i] == '(':
        i += 1
        children = []
        while tokens[i] != ')':
            child, i = parse_tokens(tokens, i)
            children.append(child)
        return children, i + 1
    elif tokens[i] == '[':
        i += 1
        children = []
        while tokens[i] != ']':
            child, i = parse_tokens(tokens, i)
            children.append(child)
        return children, i + 1
    else:
        return tokens[i], i + 1


def parse_sexp(s: str) -> list:
    tokens = tokenize_sexp(s.strip())
    result, _ = parse_tokens(tokens, 0)
    return result


# AST to Simple ----------------------------------------------------------------------

def is_lang_filter(node) -> bool:
    if not isinstance(node, list) or len(node) != 3:
        return False
    return (node[0] == '=' 
            and isinstance(node[1], list) 
            and node[1][0] == 'lang'
            and node[2] == '"en"')  # only strip English lang filters


def extract_prefix_map(ast):
    prefix_map = COMMON_PREFIXES.copy()

    if isinstance(ast, list) and ast[0] == 'prefix':
        for p in ast[1]:
            prefix = p[0].rstrip(':')
            uri = p[1][1:-1]  # strip <>
            prefix_map[prefix] = uri

    return prefix_map


def normalize_iri(token: str, prefix_map: dict) -> str:
    # blank nodes generated by Jena for [] patterns
    if token.startswith('??'):
        return '[]'

    # already full IRI
    if token.startswith("<") and token.endswith(">"):
        return token

    # variable
    if token.startswith("?"):
        return token

    # literal (including typed)
    if token.startswith('"'):
        if '^^' in token:
            val, typ = token.split('^^', 1)
            if typ.startswith("<"):
                return f"{val}^^{typ}"
            if ":" in typ:
                prefix, local = typ.split(":", 1)
                if prefix in prefix_map:
                    return f'{val}^^<{prefix_map[prefix]}{local}>'
        return token

    # prefixed IRI
    if ":" in token:
        prefix, local = token.split(":", 1)
        if prefix in prefix_map:
            return f"<{prefix_map[prefix]}{local}>"

    return token


#def uri_to_prefix(uri: str) -> str:
#    # blank nodes generated by Jena for [] patterns
#    if uri.startswith('??'):
#        return '[]'
#    
#    prefixes = {
#        #"http://www.wikidata.org/prop/direct/": "wdt:",
#        #"http://www.wikidata.org/prop/statement/": "ps:",
#        #"http://www.wikidata.org/prop/qualifier/": "pq:",
#        #"http://www.wikidata.org/prop/": "p:",
#        #"http://www.wikidata.org/entity/": "wd:",
#        #"http://www.w3.org/2000/01/rdf-schema#": "rdfs:",
#        #"http://www.w3.org/2001/XMLSchema#": "xsd:",
#        #"https://schema.org/": "schema:",
#        #"http://rdf.freebase.com/ns/": "ns:",
#    }
#    if uri.startswith('<') and uri.endswith('>'):
#        inner = uri[1:-1]
#        for full, short in prefixes.items():
#            if inner.startswith(full):
#                return short + inner[len(full):]
#    return uri


def sexp_to_str(node, prefix_map) -> str:
    if isinstance(node, str):
        return normalize_iri(node, prefix_map)
    return "(" + " ".join(sexp_to_str(child, prefix_map) for child in node) + ")"

INFIX_OPS = {'=', '!=', '<', '>', '<=', '>=', '&&', '||', '+', '-', '*', '/'}

def expr_to_str(node, prefix_map) -> str:
    """Render a filter expression in readable infix notation."""
    if isinstance(node, str):
        # handle typed literals: "val"^^<uri> or "val"^^prefix:local
        if '^^' in node:
            val, typ = node.split('^^', 1)
            return f"{val}^^{normalize_iri(typ, prefix_map) if typ.startswith('<') else typ}"
        return normalize_iri(node, prefix_map)

    if not isinstance(node, list) or not node:
        return str(node)

    op = node[0]

    if op in INFIX_OPS and len(node) == 3:
        left = expr_to_str(node[1], prefix_map)
        right = expr_to_str(node[2], prefix_map)
        return f"{left} {op} {right}"

    elif op == '!' and len(node) == 2:
        return f"!{expr_to_str(node[1], prefix_map)}"

    elif op == 'exprlist':
        # multiple conditions — render as space-separated (already cleaned of lang filters)
        return " && ".join(expr_to_str(child, prefix_map) for child in node[1:])

    elif op == 'lang':
        return f"LANG({expr_to_str(node[1], prefix_map)})"

    elif op == 'langmatches':
        return f"LANGMATCHES({expr_to_str(node[1], prefix_map)}, {expr_to_str(node[2], prefix_map)})"

    elif op == 'isliteral':
        return f"isLiteral({expr_to_str(node[1], prefix_map)})"

    elif op == 'bound':
        return f"BOUND({expr_to_str(node[1], prefix_map)})"

    elif op == 'regex':
        args = ", ".join(expr_to_str(a, prefix_map) for a in node[1:])
        return f"REGEX({args})"

    elif op == 'str':
        return f"STR({expr_to_str(node[1], prefix_map)})"

    elif op == 'in':
        left = expr_to_str(node[1], prefix_map)
        values = ", ".join(expr_to_str(v, prefix_map) for v in node[2:])
        return f"{left} IN ({values})"

    elif op == 'notin':
        left = expr_to_str(node[1], prefix_map)
        values = ", ".join(expr_to_str(v, prefix_map) for v in node[2:])
        return f"{left} NOT IN ({values})"

    elif op == 'iri':
        # Jena may prepend a file:// base URI as first arg — strip it
        args = [a for a in node[1:] 
                if not (isinstance(a, str) and a.startswith('"file://'))]
        if len(args) == 1:
            return f"IRI({expr_to_str(args[0], prefix_map)})"
        return f"IRI({expr_to_str(args[0], prefix_map)})"  # take first non-file arg

    elif op == 'concat':
        args = ", ".join(expr_to_str(a, prefix_map) for a in node[1:])
        return f"CONCAT({args})"

    elif op == 'sample':
        return f"SAMPLE({expr_to_str(node[1], prefix_map)})"

    else:
        # fallback: function call style
        args = ", ".join(expr_to_str(a, prefix_map) for a in node[1:])
        return f"{op.upper()}({args})"


def path_to_str(node, prefix_map) -> str:
    if isinstance(node, str):
        return normalize_iri(node, prefix_map)
    op = node[0]
    if op == 'path*':    return path_to_str(node[1], prefix_map) + "*"
    elif op == 'path+':  return path_to_str(node[1], prefix_map) + "+"
    elif op == 'path?':  return path_to_str(node[1], prefix_map) + "?"
    elif op == 'pathinv': return "^" + path_to_str(node[1], prefix_map)
    elif op == 'pathnot': return "!" + path_to_str(node[1], prefix_map)
    elif op in ('seq', 'pathseq'):
        return "/".join(path_to_str(c, prefix_map) for c in node[1:])
    elif op in ('alt', 'pathalt'):
        return "|".join(path_to_str(c, prefix_map) for c in node[1:])
    else:
        return sexp_to_str(node, prefix_map)


def term_to_str(term: str, prefix_map) -> str:
    """Convert a triple term (URI, prefixed name, literal, typed literal, variable) to display form."""
    if '^^' in term and term.startswith('"'):
        val, typ = term.split('^^', 1)
        return f"{val}^^{normalize_iri(typ, prefix_map) if typ.startswith('<') else typ}"
    return normalize_iri(term, prefix_map)


def collapse_extend_group(node):
    """Collapse a chain of extend nodes wrapping a group into a single group node."""
    if not (isinstance(node, list) and node[0] == 'extend'):
        return node
    
    # collect all bindings from nested extend chain
    all_bindings = []
    current = node
    while isinstance(current, list) and current[0] == 'extend':
        all_bindings.extend(current[1])
        current = current[2]
    
    if not (isinstance(current, list) and current[0] == 'group'):
        return node  # not a group at the bottom, leave unchanged
    
    # build reverse map: ?.N -> user var
    reverse = {b[1]: b[0] for b in all_bindings 
               if isinstance(b[1], str) and b[1].startswith('?.')}
    if not reverse:
        return node
    
    group_vars = current[1]
    agg_exprs = current[2]
    new_aggs = [[reverse.get(a[0], a[0]), a[1]] for a in agg_exprs]
    return ['group', group_vars, new_aggs, current[3]]

def get_internal_var_map(node, prefix_map) -> dict:
    """
    Walk a node to find the nearest group and return a map
    of internal vars (?.0, ?.1, ...) to their aggregate expressions.
    """
    if not isinstance(node, list):
        return {}
    if node[0] == 'group':
        return {agg[0]: sexp_to_str(agg[1], prefix_map) for agg in node[2]
                if isinstance(agg[0], str) and agg[0].startswith('?.')}
    # recurse into first meaningful child
    for child in node[1:]:
        result = get_internal_var_map(child, prefix_map)
        if result:
            return result
    return {}

def strip_lang_filters_from_exprlist(node) -> list | str | None:
    """
    Given a filter expression node, strip any lang filters.
    Returns the cleaned node, or None if everything was stripped.
    """
    if is_lang_filter(node):
        return None
    if not isinstance(node, list):
        return node
    if node[0] == 'exprlist':
        cleaned = [strip_lang_filters_from_exprlist(child) for child in node[1:]]
        cleaned = [c for c in cleaned if c is not None]
        if not cleaned:
            return None
        if len(cleaned) == 1:
            return cleaned[0]  # unwrap single-item exprlist
        return ['exprlist'] + cleaned
    if node[0] == '&&':
        left = strip_lang_filters_from_exprlist(node[1])
        right = strip_lang_filters_from_exprlist(node[2])
        if left is None: return right
        if right is None: return left
        return ['&&', left, right]
    return node


def split_filter_expr(node, indent: int, prefix_map) -> tuple[list[str], str | None]:
    """
    Split a filter expression into:
    - block_lines: list of block-style constructs (NOT EXISTS, EXISTS) as indented strings
    - inline_expr: remaining inline expression string, or None if nothing left
    """
    pad = "  " * indent

    if not isinstance(node, list):
        return [], expr_to_str(node, prefix_map)

    op = node[0]

    if op == 'notexists':
        body_req, body_opt = collect_blocks(node[1], indent + 1, prefix_map)
        block = f"{pad}NOT EXISTS\n" + "\n".join(body_req + body_opt)
        return [block], None

    elif op == 'exists':
        body_req, body_opt = collect_blocks(node[1], indent + 1, prefix_map)
        block = f"{pad}EXISTS\n" + "\n".join(body_req + body_opt)
        return [block], None

    elif op == 'exprlist':
        all_blocks = []
        inline_parts = []
        for child in node[1:]:
            blocks, inline = split_filter_expr(child, indent, prefix_map)
            all_blocks.extend(blocks)
            if inline:
                inline_parts.append(inline)
        inline = " && ".join(inline_parts) if inline_parts else None
        return all_blocks, inline

    elif op == '&&':
        blocks_l, inline_l = split_filter_expr(node[1], indent, prefix_map)
        blocks_r, inline_r = split_filter_expr(node[2], indent, prefix_map)
        all_blocks = blocks_l + blocks_r
        parts = [p for p in [inline_l, inline_r] if p]
        inline = " && ".join(parts) if parts else None
        return all_blocks, inline

    else:
        return [], expr_to_str(node, prefix_map)


def collect_blocks(node, indent: int, prefix_map) -> tuple[list[str], list[str]]:
    pad = "  " * indent

    if not isinstance(node, list):
        return [], []

    op = node[0]

    if op == 'join':
        req1, opt1 = collect_blocks(node[1], indent, prefix_map)
        req2, opt2 = collect_blocks(node[2], indent, prefix_map)
        return req1 + req2, opt1 + opt2

    elif op == 'project':
        # nested project = subquery
        inner = algebra_to_simple(node, indent + 1, prefix_map)
        return [f"{pad}SUBQUERY\n{inner}"], []

    elif op == 'bgp':
        lines = []
        for triple in node[1:]:
            s = term_to_str(triple[1], prefix_map)
            p = term_to_str(triple[2], prefix_map)
            o = term_to_str(triple[3], prefix_map)
            lines.append(f"{pad}{s} {p} {o}")
        return lines, []

    elif op == 'leftjoin':
        req, opt = collect_blocks(node[1], indent, prefix_map)
        pattern = node[2]
        filter_cond = node[3] if len(node) > 3 else None
        if filter_cond and is_lang_filter(filter_cond):
            filter_cond = None
        body_req, body_opt = collect_blocks(pattern, indent + 1, prefix_map)
        body_lines = "\n".join(body_req + body_opt)
        optional_block = f"{pad}OPTIONAL\n{body_lines}"
        if filter_cond:
            optional_block += f"\n{'  ' * (indent + 1)}FILTER {expr_to_str(filter_cond, prefix_map)}"
        return req, opt + [optional_block]

    elif op == 'filter':
        cleaned = strip_lang_filters_from_exprlist(node[1])
        if cleaned is None:
            return collect_blocks(node[2], indent, prefix_map)
        
        block_lines, inline_expr = split_filter_expr(cleaned, indent, prefix_map)
        req, opt = collect_blocks(node[2], indent, prefix_map)
        
        result_opt = list(opt)
        result_opt.extend(block_lines)
        if inline_expr:
            result_opt.append(f"{pad}FILTER {inline_expr}")
        
        return req, result_opt
    
    elif op == 'extend':
        # try to collapse with a nested group first
        collapsed = collapse_extend_group(node)
        if collapsed is not node:
            return collect_blocks(collapsed, indent, prefix_map)
        # plain BIND
        bindings = node[1]
        req, opt = collect_blocks(node[2], indent, prefix_map)
        bind_lines = [f"{pad}BIND {expr_to_str(b[1], prefix_map)} AS {b[0]}" for b in bindings]
        return bind_lines + req, opt

    elif op == 'table':
        var_decl = node[1]
        variables = var_decl[1:]
        rows = node[2:]
        lines = [f"{pad}VALUES {' '.join(variables)}"]
        for row in rows:
            bindings = row[1:]
            binding_dict = {b[0]: sexp_to_str(b[1], prefix_map) for b in bindings}
            values = " ".join(binding_dict.get(var, "UNDEF") for var in variables)
            lines.append(f"{pad}  {values}")
        return lines, []

    elif op == 'group':
        group_vars = node[1]
        
        # Jena omits the agg list when there are no aggregates
        # (group (vars) body) vs (group (vars) ((aggs)) body)
        if len(node) == 3:
            # no aggregates
            agg_exprs = []
            body = node[2]
        else:
            agg_exprs = node[2]
            body = node[3]
        
        body_req, body_opt = collect_blocks(body, indent, prefix_map)
        lines = []
        if group_vars:
            lines.append(f"{pad}GROUP BY {' '.join(group_vars)}")
        for agg in agg_exprs:
            var = agg[0]
            raw_expr = agg[1]
            if isinstance(raw_expr, list) and raw_expr[0] == 'count' and len(raw_expr) == 1:
                expr = "COUNT(*)"
            else:
                expr = expr_to_str(raw_expr, prefix_map)
            if not var.startswith('?.'):
                lines.append(f"{pad}{expr} AS {var}")
        lines.extend(body_req + body_opt)
        return lines, []

    elif op == 'sequence':
        req, opt = [], []
        for child in node[1:]:
            r, o = collect_blocks(child, indent, prefix_map)
            req.extend(r)
            opt.extend(o)
        return req, opt

    elif op == 'path':
        subject = normalize_iri(node[1], prefix_map)
        path_expr = path_to_str(node[2], prefix_map)
        obj = normalize_iri(node[3], prefix_map)
        return [f"{pad}{subject} {path_expr} {obj}"], []

    elif op == 'union':
        left_req, left_opt = collect_blocks(node[1], indent, prefix_map)
        right_req, right_opt = collect_blocks(node[2], indent, prefix_map)
        return left_req + left_opt + [f"{pad}UNION"] + right_req + right_opt, []

    elif op == 'minus':
        req, opt = collect_blocks(node[1], indent, prefix_map)
        minus_req, minus_opt = collect_blocks(node[2], indent + 1, prefix_map)
        minus_body = "\n".join(minus_req + minus_opt)
        minus_block = f"{pad}MINUS\n{minus_body}"
        return req, opt + [minus_block]

    else:
        return [algebra_to_simple(node, indent, prefix_map)], []


BODY_OPS = {'join', 'leftjoin', 'bgp', 'filter', 'extend', 'table', 'group', 'sequence', 'path', 'union', 'minus'}

def algebra_to_simple(node, indent=0, prefix_map={}) -> str:
    pad = "  " * indent
    if isinstance(node, str):
        return pad + normalize_iri(node, prefix_map)
    op = node[0]
    if op == 'prefix':
        return algebra_to_simple(node[2], indent, prefix_map)
    elif op == 'project':
        variables = " ".join(node[1])
        child = node[2]
        lines = [f"{pad}SELECT {variables}"]
        # peel ORDER
        order_line = None
        if isinstance(child, list) and child[0] == 'order':
            order_conds = child[1]
            internal_map = get_internal_var_map(child[2], prefix_map)
            order_parts = []
            for c in order_conds:
                if isinstance(c, list):
                    direction = c[0].upper()
                    var = c[1]
                    var_str = internal_map.get(var, var)
                    order_parts.append(f"{direction} {expr_to_str(var_str, prefix_map) if isinstance(var_str, list) else var_str}")
                else:
                    var_str = internal_map.get(c, c)
                    order_parts.append(expr_to_str(var_str, prefix_map) if isinstance(var_str, list) else var_str)
            order_line = f"{pad}ORDER {' '.join(order_parts)}"
            child = child[2]
        while isinstance(child, list) and child[0] == 'filter':
            cleaned = strip_lang_filters_from_exprlist(child[1])
            if cleaned is None:
                child = child[2]
            else:
                break
        child = collapse_extend_group(child)
        req, opt = collect_blocks(child, indent + 1, prefix_map)
        lines.extend(req + opt)
        if order_line:
            lines.append(order_line)
        return "\n".join(lines)
    elif op == 'distinct':
        inner = algebra_to_simple(node[1], indent, prefix_map)
        return inner.replace("SELECT ", "SELECT DISTINCT ", 1)
    elif op == 'slice':
        offset = None if node[1] == '_' else node[1]
        limit  = None if node[2] == '_' else node[2]
        body   = algebra_to_simple(node[3], indent, prefix_map)
        suffix = ""
        if offset: suffix += f"\n{pad}OFFSET {offset}"
        if limit:  suffix += f"\n{pad}LIMIT {limit}"
        return f"{body}{suffix}"
    elif op in BODY_OPS:
        # if we reach here from the top level (not via collect_blocks),
        # it means there's no project wrapper — this is an ASK query
        if indent == 0:
            req, opt = collect_blocks(node, indent + 1, prefix_map)
            return "\n".join(["ASK"] + req + opt)
        else:
            req, opt = collect_blocks(node, indent, prefix_map)
            return "\n".join(req + opt)
    else:
        raise ValueError(f"Unknown algebra op: {op!r} in node: {node}")


if __name__ == "__main__":
    import sys
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("dataset_path", help="Path to dataset JSON file")
    args = parser.parse_args()

    with open(args.dataset_path, "r", encoding="utf-8") as f:
        dataset = json.load(f)

    if True:
        total = len(dataset)
        failed = 0
        skipped = 0

        for i, entry in enumerate(dataset):
            sparql_query = entry.get("sparql", "").strip()
            if not sparql_query:
                entry["Sexpr"] = "Parsing failed"
                skipped += 1
                continue

            question_id = entry.get("id") or entry.get("ID", "Unknown")
            print(f"[{i+1}/{total}] {question_id}", end=" ... ", flush=True)

            try:
                sparql_query_fixed = fix_sparql_for_jena(sparql_query)
                algebra = sparql_to_algebra(sparql_query_fixed)
                if not algebra:
                    raise RuntimeError("Jena returned no output")

                ast = parse_sexp(algebra)
                prefix_map = extract_prefix_map(ast)
                simple = algebra_to_simple(ast, prefix_map=prefix_map)
                entry["Sexpr"] = simple
                print("OK")

            except Exception as e:
                entry["Sexpr"] = "Parsing failed"
                failed += 1
                print(f"FAILED ({e})")


        # write to file
        input_path = args.dataset_path

        # normalize path
        input_path = os.path.normpath(input_path)
        parts = input_path.split(os.sep)

        # expect: data/{dataset}/origin/{file}
        try:
            data_idx = parts.index("data")
            dataset_name = parts[data_idx + 1]
            filename = parts[-1]
        except (ValueError, IndexError):
            raise RuntimeError(f"Unexpected dataset path format: {input_path}")

        name, ext = os.path.splitext(filename)

        output_dir = os.path.join("data", dataset_name, "sexpr")
        os.makedirs(output_dir, exist_ok=True)

        output_path = os.path.join(output_dir, f"{name}_sexpr{ext}")
        
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(dataset, f, indent=2, ensure_ascii=False)

        print(f"\nDone. {total - failed - skipped}/{total} succeeded, "
            f"{failed} failed, {skipped} skipped (no SPARQL).")
        print(f"Saved to {output_path}")

    else:
        failures = []
        for entry in dataset:
            try:
                sparql = fix_sparql_for_jena(entry.get("sparql", ""))
                algebra = sparql_to_algebra(sparql)
                if algebra:
                    ast = parse_sexp(algebra)
                    prefix_map = extract_prefix_map(ast)
                    simple = algebra_to_simple(ast, prefix_map=prefix_map)
            except Exception as e:
                failures.append((entry.get("id"), str(e), algebra if algebra else "JENA FAILED"))

        for id, err, alg in failures:
            print(f"\n=== {id} ===")
            print(f"Error: {err}")
            print(f"Algebra: {alg}")