### Model
#model_name_or_path: LLMs/Models/Qwen25-7b-hf/
model_name_or_path: LLMs/Models/llama-2-13b/


### Method
stage: sft
do_train: true
finetuning_type: lora

### LoRA config
lora_target: all
lora_rank: 32
lora_alpha: 64
lora_dropout: 0.1

### Dataset
dataset: CWQ_train.sparql  
dataset_dir: LLMs/data    

#template: qwen 
template: llama2               

cutoff_len: 2048
max_samples: 50000

### Output
output_dir: LLMs/MyModels/Llama-2-13b_CWQ-sparql/
logging_steps: 10
save_steps: 500
overwrite_output_dir: true

### Training
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 5e-5
num_train_epochs: 100
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true

### Evaluation (optional)
val_size: 0.01
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 500