### Model
model_name_or_path: LLMs/Models/Qwen25-7b-hf/

### Method
stage: sft
do_train: true
finetuning_type: lora

### LoRA config
lora_target: q_proj,v_proj

### Dataset
dataset: WWQ_train.sparql
eval_dataset: WWQ_dev.sparql
dataset_dir: LLMs/data
template: qwen
overwrite_cache: true

### Output
output_dir: LLMs/MyModels/Qwen25-7b_WWQ-sparql/
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: true

### Training
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 5e-6
num_train_epochs: 100.0
lr_scheduler_type: cosine
fp16: true

### Evaluation
eval_strategy: steps
eval_steps: 1000
load_best_model_at_end: true
metric_for_best_model: eval_loss
greater_is_better: false